package org.folio.factory.core.domain;

public enum AuditEventType {
    EXECUTION_STARTED,
    EXECUTION_COMPLETED,
    STATE_TRANSITION,
    STEP_STARTED,
    STEP_COMPLETED,
    STEP_FAILED,
    RETRY_SCHEDULED,
    ESCALATED,
    ARTIFACT_WRITTEN,
    HITL_REQUESTED,
    HITL_DECIDED,
    SUBFLOW_INVOKED,
    SUBFLOW_RETURNED,
    CONNECTOR_ACTION,
    CONNECTOR_SKIPPED,
    EXECUTION_DEDUPED,
    EXECUTION_BUDGET_EXCEEDED,
    RETENTION_PURGED
}
